# The default project name is the basename of the project directory. 
# You can set a custom project name by using the -p command line option 
# or the COMPOSE_PROJECT_NAME environment variable.
# Example: docker-compose -p projectName up -d

version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.15.3
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
            rawAccess: false
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      # Can set another path 
      - mysql:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.24.0.20
volumes:
  mysql:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16